# Generated by Django 4.2 on 2025-03-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('layer_type', models.CharField(choices=[('Polyline', 'Polyline'), ('Polygon', 'Polygon')], max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/layers/file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('label_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
