# Generated by Django 4.2 on 2025-03-21 11:51

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0002_alter_location_audio_alter_location_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Points",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.IntegerField()),
                ("image_name", models.CharField(max_length=255, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="media/locations/image/blank.jpg",
                        null=True,
                        upload_to="media/locations/image",
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True, null=True, upload_to="media/locations/audio"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="media/locations/video"
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "point_type",
                    models.CharField(
                        choices=[("NEW", "New"), ("OLD", "Old")],
                        default="NEW",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
