# Generated by Django 4.2 on 2025-03-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_points_delete_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="points",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
