# Generated by Django 4.2 on 2025-03-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_profile_first_name_alter_profile_last_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="national_id",
        ),
    ]
